site_name: "frostyard"
site_url: https://frostyard.github.io/
theme:
  name: material

plugins:
  - monorepo
  - search

nav:
  - Home: index.md
  - Atomic Linux:
    - What Is It?: atomic.md
  - Images:
    - Snow: '!include ./snow/mkdocs.yml'
  - Tools:
    - nbc: '!include ./nbc/mkdocs.yml'
    - chairlift: '!include ./chairlift/mkdocs.yml'
